export const LIST_ITEMS = 'LIST_ITEMS'

export const LIST_ITEMS_ERROR = 'LIST_ITEMS_ERROR'
export const CREATE_ITEM_ERROR = 'CREATE_ITEM_ERROR'
export const REMOVE_ITEM_ERROR = 'REMOVE_ITEM_ERROR'

export const LIST_ITEMS_SUCCESS = 'LIST_ITEMS_SUCCESS'
export const CREATE_ITEM_SUCCESS = 'CREATE_ITEM_SUCCESS'
export const REMOVE_ITEM_SUCCESS = 'REMOVE_ITEM_SUCCESS'

export const LIST_ITEMS_PENDING = 'LIST_ITEMS_PENDING'
export const CREATE_ITEM_PENDING = 'CREATE_ITEM_PENDING'
export const REMOVE_ITEM_PENDING = 'REMOVE_ITEM_PENDING'
